### ISSUE TITLE
image with insert module

### ISSUE THREAD

**Issue by coolman7** [signalpoint/colorbox#1]
On drupal side, I use insert and colorbox modules for pictures inside articles. So I upload pictures to node, insert them with insert button comes with insert module, and insert them a place inside full HTML editor where as I wanted. And pictures are shown with colorbox module.

On drupalgap side, I added colorbox module to project, but when I open the node created as explained above, does not show pictures inserted with insert button. It show HTML article, no problem. Picrures are shown as blank rectangles. If I click that blank rectangle, it shows the picture full screen. But I cannot go back with back button of android.

I'm using latest snapshot from github project. What should I do to display images inserted with insert button? And what should I do to return to node with back button.

Thanks
![screenshot_2015-08-19-10-10-33](https://cloud.githubusercontent.com/assets/11715129/9350624/04ccd382-465b-11e5-897f-91380868a742.png)

**Comment by signalpoint** [comment]
@coolman7 If you inspect the HTML src of the image, what does it look like?

**Comment by coolman7** [comment]
```
<a class="colorbox colorbox-insert-image" href="http://<removed>.com/sites/<removed>.com/files/tutorial_picture/pic3.jpg" rel="gallery-all" style="font-size: 13.0080003738403px; font-weight: normal; line-height: 1.538em;"><img alt="" class="image-medium article-image" src="/sites/<removed>.com/files/styles/medium/public/tutorial_picture/pic3.jpg?itok=zWUr34m6" style="width: 220px; height: 130px;" /></a>
```

**Comment by signalpoint** [comment]
@coolman7 That's the HTML inspect from inside the app? If so, you'll notice the `src` on the image is a relative path, and DrupalGap won't know where to load that image from. This module is probably what you're looking for: http://drupalgap.org/project/pathfix

**Comment by coolman7** [comment]
no. it is from web page. but I think mobile app should have same html. I'll try that module and let you know if it fixes.

**Comment by coolman7** [comment]
I don't find git path for drupal sandbox module to download. Please write git address for drupal sandbox module.
thanks

**Comment by signalpoint** [comment]
@coolman7 https://www.drupal.org/project/2068317/git-instructions

**Comment by coolman7** [comment]
Ok. I found the problem. It was about full path setting of insert module. I set Use absolute paths on insert and re-insert all images. Problem solved. There is no need to install pathfix module.
Thanks for help.
